### ISSUE TITLE
Support additional exception schemas

### ISSUE THREAD

**Issue by captaincoordinates** [radiantearth/stac-api-spec#347]
Based on [this section](https://github.com/radiantearth/stac-api-spec/blob/main/core/commons.yaml#L16) of the OpenAPI spec it appears that STAC API implementations should only support a single type of error response with the following schema:

```yml
    exception:
      type: object
      description: |-
        Information about the exception: an error code plus an optional description.
      required:
        - code
      properties:
        code:
          type: string
        description:
          type: string
```

A change was [recently made](https://github.com/stac-utils/stac-fastapi/pull/361) in stac-fastapi to conform to the spec and it had undesirable consequences for parameter validation on API requests. Because all error detail must be contained in a single string property the response can no longer be easily parsed to identify which fields failed validation and why. Forcing all detail into a single string makes parsing it more complex and can present new challenges for STAC API clients to inform users of validation errors.

Can the STAC API spec support additional exception schemas to better support parameter validation?

Below are two example responses with parameter validation errors showing how conforming to the spec has limited the response's value.

Spec-Compliant (stac-fastapi 2.4.1)
```json
{
  "code": "RequestValidationError",
  "description": "3 validation errors for Request\nbody -> bbox\n  wrong tuple length 3, expected 4 (type=value_error.tuple.length; actual_length=3; expected_length=4)\nbody -> bbox\n  wrong tuple length 3, expected 6 (type=value_error.tuple.length; actual_length=3; expected_length=6)\nbody -> limit\n  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)"
}
```

Non-Spec-Compliant (stac-fastapi 2.3.0)
```json
{
  "detail": [
    {
      "loc": [
        "body",
        "bbox"
      ],
      "msg": "wrong tuple length 3, expected 4",
      "type": "value_error.tuple.length",
      "ctx": {
        "actual_length": 3,
        "expected_length": 4
      }
    },
    {
      "loc": [
        "body",
        "bbox"
      ],
      "msg": "wrong tuple length 3, expected 6",
      "type": "value_error.tuple.length",
      "ctx": {
        "actual_length": 3,
        "expected_length": 6
      }
    },
    {
      "loc": [
        "body",
        "limit"
      ],
      "msg": "ensure this value is greater than 0",
      "type": "value_error.number.not_gt",
      "ctx": {
        "limit_value": 0
      }
    }
  ]
}
```
